In [1]:
import numpy as np

In [2]:
a=np.array([[1,6], [2,8], [3,11], [3,10], [1,7]])

In [3]:
mean_a=np.zeros(2,)

In [4]:
np.mean(a, axis=0, out=mean_a)

array([2. , 8.4])

In [5]:
mean_a

array([2. , 8.4])

In [6]:
a_centered=a-mean_a

In [7]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [8]:
a_centered_sp=a_centered[0:,0]@a_centered[0:,1]

In [9]:
a_centered_sp

8.0

In [10]:
x=a_centered_sp/(a_centered.shape[0] - 1)

In [11]:
x

2.0

In [12]:
np.cov(a.T)[0, 1]

2.0

In [13]:
#### Pandas

In [14]:
import pandas as pd

In [15]:
authors = pd.DataFrame({'authorid':[1,2,3],'author_name':['Тургенев', 'Чехов', 'Островский']}, columns=['authorid','author_name'])

In [16]:
book = pd.DataFrame({'authorid':[1,1,1,2,2,3,3],'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий','Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 'price':[450, 300, 350, 500, 450, 370, 290]}, columns=['authorid','book_title', 'price'])

In [17]:
book

authorid            book_title  price
0         1           Отцы и дети    450
1         1                 Рудин    300
2         1     Дворянское гнездо    350
3         2      Толстый и тонкий    500
4         2       Дама с собачкой    450
5         3                 Гроза    370
6         3  Таланты и поклонники    290

In [18]:
authors_price=pd.merge(authors, book, on='authorid', how='inner')

In [19]:
authors_price

authorid author_name            book_title  price
0         1    Тургенев           Отцы и дети    450
1         1    Тургенев                 Рудин    300
2         1    Тургенев     Дворянское гнездо    350
3         2       Чехов      Толстый и тонкий    500
4         2       Чехов       Дама с собачкой    450
5         3  Островский                 Гроза    370
6         3  Островский  Таланты и поклонники    290

In [20]:
top5=authors_price.sort_values(by='price', ascending=False).head(5)

In [21]:
top5

authorid author_name         book_title  price
3         2       Чехов   Толстый и тонкий    500
0         1    Тургенев        Отцы и дети    450
4         2       Чехов    Дама с собачкой    450
5         3  Островский              Гроза    370
2         1    Тургенев  Дворянское гнездо    350

In [22]:
authors_stat=authors_price.groupby('author_name').agg({'price': ['mean', 'min', 'max']})
authors_stat = authors_stat.rename(columns={'min':'min_price', 'max':'max_price', 'mean':'mean_price'})

In [23]:
authors_stat

price                    
             mean_price min_price max_price
author_name                                
Островский   330.000000       290       370
Тургенев     366.666667       300       450
Чехов        475.000000       450       500

In [24]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

In [25]:
authors_price

authorid author_name            book_title  price    cover
0         1    Тургенев           Отцы и дети    450  твердая
1         1    Тургенев                 Рудин    300   мягкая
2         1    Тургенев     Дворянское гнездо    350   мягкая
3         2       Чехов      Толстый и тонкий    500  твердая
4         2       Чехов       Дама с собачкой    450  твердая
5         3  Островский                 Гроза    370   мягкая
6         3  Островский  Таланты и поклонники    290   мягкая

In [26]:
book_info = pd.pivot_table(authors_price, values='price', index=['author_name'], columns=['cover'], aggfunc=np.sum)
book_info['мягкая'] = book_info['мягкая'].fillna(0)
book_info['твердая'] = book_info['твердая'].fillna(0)

In [27]:
book_info

cover        мягкая  твердая
author_name                 
Островский    660.0      0.0
Тургенев      650.0    450.0
Чехов           0.0    950.0